// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID            int32            `json:"id"`
	UserID        int64            `json:"user_id"`
	TransactionID string           `json:"transaction_id"`
	SourceType    string           `json:"source_type"`
	State         string           `json:"state"`
	Amount        pgtype.Numeric   `json:"amount"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int64            `json:"id"`
	Balance   pgtype.Numeric   `json:"balance"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
