// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetTransaction(ctx context.Context, transactionID string) (Transaction, error)
	GetTransactionsByUser(ctx context.Context, userID int64) ([]Transaction, error)
	GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error)
	GetUserForUpdate(ctx context.Context, id int64) (User, error)
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error
}

var _ Querier = (*Queries)(nil)
